### ISSUE TITLE
Reestablish dead connection

### ISSUE THREAD

**Issue by jayshepherd** [psequel/psequel#73] opened 2015-10-28 19:05 UTC
If for some reason (such as closing laptop, moving to a new location and opening laptop) the connection dies, it would be nice to be able to re-establish the connection.

Currently, the only way I see to resume work is to: 

1. Copy the contents of my query entry box
2. Close the window
3. Open a new window to establish a new connection
4. Paste my query

![monosnap 2015-10-28 13-59-36](https://cloud.githubusercontent.com/assets/4238/10799708/354f4d3e-7d7c-11e5-897e-16166a319adc.png)

**Comment by Lidor7** [comment] 2015-10-30 16:56
Yes, this would be fantastic.  I have the same issue.  It seemed like this used to work in previous versions.  I'm currently using Version 1 (1.3.2).

**Comment by bryanhorne** [comment] 2015-11-03 19:52
+1

**Comment by psequel** [comment] 2015-11-07 07:41
Duplicate of #64

**Closed by psequel** 2015-11-07 07:41 UTC
Labels: duplicate

**Comment by 2hp** [comment] 2016-03-16 20:00
+1
