### ISSUE TITLE
Autocomplete moves cursor to next non-blank line after delay

### ISSUE THREAD

**Issue by jayshepherd** [psequel/psequel#75] opened 2015-11-07 16:48 UTC
When you are typing a query and you pause after typing a reserved word, it will auto-complete and then move the cursor to the beginning next line that is not blank.

![d72im75o0a5uol 2015-11-07 10-46-43](https://cloud.githubusercontent.com/assets/4238/11016129/121463ae-853d-11e5-9ad5-f1d8ebb966f6.png)

**Comment by psequel** [comment] 2015-11-10 06:38
I cannot reproduce this. Could you describe in details the steps to reproduce this bug? [Please include your OS X, PostgreSQL and PSequel versions when reporting a bug.](https://github.com/psequel/psequel#how-do-i-report-bugs-or-suggest-new-features)

**Comment by jayshepherd** [comment] 2015-11-11 16:29
* PSequel: Version 1 (1.3.4)
* OSX: Version 10.11.1 (15B42)
* PostgreSQL: 9.4.2 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3, 64-bit

I may have confused things by using the term Auto Complete instead of Auto Format. Anyway, here is a detailed list of steps to reproduce what I'm seeing. Keep in mind that this example is trivial, but seems to reproduce the behavior.  It's more confusing when going back and editing a query and having it move the cursor to an unexpected location.

Steps for me to reproduce:

1) Connect to server with a new window
2) Switch to Query Tab
3) Clear out the window text (CMD+A, DELETE)
4) Press enter twice (creating three lines visible)

![d72im75o0a5uol 2015-11-11 10-22-29](https://cloud.githubusercontent.com/assets/4238/11096124/1dfcc37c-885e-11e5-9c85-3e396367ef55.png)

5) Go back to first line and start typing `select * from ` and stop typing after a space after the word `from`

![d72im75o0a5uol 2015-11-11 10-23-30](https://cloud.githubusercontent.com/assets/4238/11096160/441f0fba-885e-11e5-869b-517f10b63a2d.png)

6) Observe the auto-formatting moving the cursor.

Also, it seems to happen after only certain words such as `FROM` or `AS`

If you need more info, maybe I can record a video or something.

**Comment by erictrinh** [comment] 2016-01-05 18:35
This is happening to me as well. Extremely annoying when editing the middle of a query.

PSequel: 1.4.0
OSX: 10.11.2 (15C50)
PostgreSQL: 9.4.4

**Comment by t1ag0** [comment] 2016-01-14 14:09
Same here:
PSequel: 1.4.0
OSX:10.11.2
PosgreSQL : 9.2.7

**Comment by s2t2** [comment] 2016-01-29 23:50
I'm so glad there is an existing issue because this bug is wrecking my productivity :snail:

**Comment by psequel** [comment] 2016-02-09 00:15
Fixed in v1.4.1

**Closed by psequel** 2016-02-09 00:15 UTC
Labels: bug
