### ISSUE TITLE
I ran db:seed then when I went to open the connection it immediately crashes. 

### ISSUE THREAD

**Issue by devbriguy** [psequel/psequel#93] opened 2016-01-14 15:23 UTC
From the Apple report: 
/Applications/PSequel.app/Contents/Frameworks/psqlodbcw.so
Performing @selector(connectToDb:) from sender PSequel.SpinnerButton 

Mac OSX 10.10.5 
PSequel 1.4.0

**Comment by psequel** [comment] 2016-01-15 06:25
Duplicate of #89

**Closed by psequel** 2016-01-15 06:25 UTC
Labels: duplicate
