### ISSUE TITLE
psequel content view not rendered on Mac OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by davidthewatson** [psequel/psequel#95] opened 2016-01-18 21:10 UTC
I'm running psequel 1.4.0 on Mac OS X 10.11 El Capitan. I have an existing schema in my local postgresql 9.5 instance. I can connect with psql to that instance and view the describe the schema with \d. However, when I connect via psequel, the content view does not render properly. I have the same setup on another Mac OS X 10.10 Yosemite machine and it renders fine. Only difference is the OS and PostgreSQL version 9.4.1 on the Yosemite installed.

![screen shot 2016-01-18 at 4 06 27 pm](https://cloud.githubusercontent.com/assets/150892/12402828/9b78f6de-bdfd-11e5-9207-66f852c23390.png)

**Comment by davidthewatson** [comment] 2016-01-18 21:12
Turns out the rendering bug is that the splitter is jammed hard left. When I dragged it away from the leftmost edge, the tables were there. Perhaps it's painting before it gets the table data?

**Comment by psequel** [comment] 2016-03-27 02:35
Duplicate of #81

**Closed by psequel** 2016-03-27 02:35 UTC
Labels: duplicate
