### ISSUE TITLE
SSH Tunnel Error

### ISSUE THREAD

**Issue by redolent** [psequel/psequel#121] opened 2016-07-05 21:06 UTC
I'm getting this error, and I have no idea how to address it... is this a bug? Or is the program thinking it's an error when it's not? Please help :)

SSH Host: <1.2.3.4>
SSH Port: 22
SSH User: ec2-user
Identity File: </Users/allan/somewhere/secret.pem>

Screenshot: http://imgur.com/HORcZhI

```
SSH Tunnel Error

OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /Users/allan/.ssh/config
debug1: /Users/allan/.ssh/config line 4: Applying options for 54.200.179.234
debug1: /Users/allan/.ssh/config line 19: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 20: Applying options for *
debug1: /etc/ssh/ssh_config line 102: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Requesting forwarding of local forward LOCALHOST:61617 -> pma.dmtinstitute.com:5432
debug1: mux_client_request_session: master session id: 15

```

**Comment by psequel** [comment] 2016-07-06 03:51
The app expects the string "Entering interactive session" in order to know ssh tunnel is connected.

**Comment by ausiddiqui** [comment] 2016-07-27 03:22
i have my postgresql server on digital ocean and have ssh key without a passphrase setup, but i can't seem to connect to it. there's no way to just use the username and password, like how i connect through terminal to ssh?

**Comment by ausiddiqui** [comment] 2016-07-27 18:31
never mind, the command line ssh tunnel on terminal seems to work fine, for anyone else who runs into this issue because they were expecting a different interface, here's what i did FYI:

`ssh -NC username@public.ip.address.ofpostgresql.server -L <local port to tunnel to>:127.0.0.1:<default postgresql port>
ssh -NC root@99.99.999.99 -L 6001:127.0.0.1:5432`

enter the password to get into 99.99.999.99 for the user 'root'

on the login window in psequel just connect to 127.0.0.1 at port 6001 and use the postgresql db username and password, no need for ssh/ssl authentication.

**Comment by psequel** [comment] 2016-11-20 05:41
Since you have a solution for that, I'm closing this issue for now.

**Closed by psequel** 2016-11-20 05:41 UTC

**Comment by rspeed** [comment] 2018-03-07 16:16
For future reference, this issue is caused by using a `ControlMaster`, which muxes multiple SSH sessions together into a single connection. One downside of this feature is that setting up port forwarding on an existing connection [requires a different command](https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing#Port_Forwarding_After_the_Fact) which acts directly on the local socket.

For PSequel to manage this edge case is *probably* possible, but I'm not sure how difficult it would be. It would have to detect that there's an existing connection, determine the path of the socket, then send the modified command.

**Comment by rspeed** [comment] 2018-03-07 16:50
Geez, I should have researched more before leaving that comment. There are apparently two options:

## Add a new forwarded port to the connection

You can check for the existence of a muxed connection using this command: `ssh -O check {hostname}`

If there's no ControlMaster configured, the exit will be 255. In that case, everything is hunky-dory and you can connect like normal.

On the other hand, it'll have a success exit code (0) if a connection exists. The tricky part is getting the path to the socket, but I'm looking into it now.

Once you have that path, use the alternate version of the ssh command which interacts with the socket.


## Tell OpenSSH to ignore existing connections

This one is super easy: add `-S none` to the command. That tells `ssh` to create a new connection regardless of whether or not one already exists. The obvious downside is that you lose the benefits of the shared connection.
