### ISSUE TITLE
Consistently crashes when the Connect button is clicked on the new connection screen

### ISSUE THREAD

**Issue by t-anjan** [psequel/psequel#124] opened 2016-07-11 11:21 UTC
Hello,

I have PostgreSQL 9.5 installed from here: http://postgresapp.com/ . By default, the username is my Mac account username. It has no password. Runs on port 5432.

On the PSequel new connection screen, when I give the above details and click on "Connect", PSequel just crashes. Please find the crash report attached.

[PSequel_2016-07-11-163801_Anjan-Macasaurus.crash.zip](https://github.com/psequel/psequel/files/356943/PSequel_2016-07-11-163801_Anjan-Macasaurus.crash.zip)

**Comment by psequel** [comment] 2016-07-12 05:33
Duplicate of #106

**Closed by psequel** 2016-07-12 05:33 UTC

**Comment by t-anjan** [comment] 2016-07-12 06:46
Oops, sorry about the duplicate.
